
// Objective-C API for talking to the following Go packages
//
//	github.com/lightningnetwork/lnd/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Lndmobile_FRAMEWORK_H__
#define __Lndmobile_FRAMEWORK_H__

#include "Lndmobile.objc.h"
#include "Universe.objc.h"

#endif
