name: unit-tests-android

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  tests-android:
    name: Android Unit Tests
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node_modules
        working-directory: example
        run: yarn install && yarn rn-setup

      - name: Use JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Use Android SDK
        uses: android-actions/setup-android@v2

      - name: Run Android unit tests
        working-directory: lib/android
        run: ./gradlew testDebugUnitTest --stacktrace --no-daemon
